apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  labels:
    app: movie-catalog-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
      - name: movie-catalog-container
        image:  akyhcs/movie-catalog-ms:latest
        ports:
        - containerPort: 8082
         
---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  labels:
    app: movie-catalog-service
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: movie-catalog-service
