apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-data-service
  labels:
    app: ratings-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-data-service
  template:
    metadata:
      labels:
        app: ratings-data-service 
    spec:
      containers:
      - name: ratings-data-service
        image: akyhcs/movie-rating-microservice:latest
        ports:
        - containerPort: 8081
        env:
        - name: mysqlservice
          value: mysql-service
---
apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service
  labels:
    app: ratings-data-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: ratings-data-service
